spring:
  application:
    name: netflix-zuul-api-gateway-server

server:
  port: 8765

eureka:
  instance:
    perferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    item-service: /item/**
    user-service: /user/**
  ignored-services: '*'
  prefix: /api

#logging:
#  level:
#    com.netflix: WARN
#    org.springframework.web: WARN
#    com.itemsSharing: DEBUG
