spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false
    dbcp2:
      validation-query: SELECT 1
      test-on-borrow: true
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}

  jackson:
    serialization:
      fail-on-empty-beans: false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  logging:
    path: application.log

server:
  port: 8082