spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lakith/cloud-config.git
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}

server:
  port: 8888
